### PR TITLE
Added support for CRM 2016 on-premises IFD

### PR DESCRIPTION
**Pull request by aledkov**
Hi Jason.

Take a look at my solution for this issue: https://github.com/jlattimer/CRMDeveloperExtensions/issues/60
I have got the same error after upgrading our IFD on-premises systems to CRM 2016. I'm not sure I have done it in the right way, but it works. I tested it on CRM 2011, 2013, 2016. 

As you know Microsoft.Xrm.Client.dll was removed from CRM 2016 SDK and now you should use Microsoft.Xrm.Tooling.Connector namespace. 

**One important thing. You should add organization name at the end of URL. For example: https://host.domain.com/orgname. CrmServiceClient works in that way.** 

Unfortunately with existing nuget packages for CRM 2016 assemblies I have got an error:

image

So I just added all required dll's to Reference folder. Maybe it is not a good way, but it works for me.

### CODE REVIEW

**Comment by gebrom** [comment]
Same issue here :-(

**Comment by jlattimer** [comment]
Jus catching up...
I've tested this and I've gotten it to work for CRM 2016 Online 8.2 and CRM 2011 On Premise w/ IFD. When I attempt to connect to 2013 or 2015 IFD orgs. the OrganizationServiceProxy of the CrmServiceClient  always ends up being null. 

Tried all variations of urls w/ and w/o org name, username & domain formats. In the 2011 org I used to be able to sign in using an email address but the connection here only succeeds if I used domain and username separately. 

Still investigating...

**Comment by jlattimer** [comment]
Well apparently I didn't try all variations of domain and username - it seems that in my 2011 org. specifying DOMAIN in the connection string was not required - I was able to get away with USERNAME  = domain\username. In my 2013 and 2015 orgs. I needed to specify DOMAIN and have USERNAME  = domain\username. 

I'll merge this and then make some updated to the connection window to reflect the new requirements to help people out trying to enter all this. 

Thanks!!

PS: Bonus points if you could make the XRM Tooling Common Login Control from the SDK work in this project so we could just

**Comment by aledkov** [comment]
Hmm... strange enough, with correct orgname after last slash in Url part of the connection string it works fine for IFD 2011, 2013, 2016. I use it every day. But I had no chance to test it with online and non IFD implementations.
Good idea about XRM Tooling Control, surely it worth being checked.

**Comment by jlattimer** [comment]
Would you be able to test if you're able to connect to your orgs. with both the domain field populated with the domain and username populated with domain\username? If it also works in your orgs. I'll make that the standard.

**Comment by aledkov** [comment]
Yes, username=domain\username works fine for me, as well as just username without domain. But it only works if orgname is specified after last slash in url. Tested for 2011, 2013, 2016 IFD.

**Pull request merged**
