### PR TITLE
Refactored Connection Pane into its own UserControl

### PR DESCRIPTION
**Pull request by mike9182**
I Refactored the Plugin Deployer Connection Pane into its own UserControl in a shared library. I am planning to refactor the Report Deployer and Web Resource Deployer to also use this UserControl.

### CODE REVIEW

**Comment by jlattimer** [comment]
I have a more pressing items to get done over the next couple days - but later in the week I'll take a look!!

**Comment by mike9182** [comment]
That sounds good. I was looking back at the number of insertions and deletions and noticed something seemed off. Then I realized that I had forgotten to commit a few files. We use SVN where I work so I'm still getting used to Git.

**Comment by mike9182** [comment]
Do you know when you'll get a chance to look at this?

**Comment by jlattimer** [comment]
Thanks for helping out - I really, really appreciate it! FYI I've also started a new tool windows for using the Solution Packager tool. So if you're feeling ambitious you could refactor it with the new connection usercontrol :+1:

**Pull request merged**
